---
title: 'Análisis de datos: Netfliz Prize Program'
author: "Laura Basalo Tur, Camila Pérez"
date: "20/11/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


#Introducción

TODO: Comentar...


#Carga de datos

TODO: Comentar...

```{r}
rm(list=ls())
cat("\014") ## limpia la pantalla del R

#Se importan 'n' observaciones del conjunto de datos 'Netflix Prize data'
n = 10000
dataframe = read_tsv("data/combined_data_1.txt", col_names=FALSE, n_max = n)

#Se asigna una posición a cada observación para posteriormente indicar el id de película de cada una de ellas
dataframe = dataframe %>% 
            mutate(row=row_number()) 
rows = grep(":", dataframe$X1) 
rows_ID = dataframe %>% 
         filter( row %in% rows ) 
IDs = unique(rows_ID$X1)
reps = diff(c(rows_ID$row,max(dataframe$row)+1))

df = dataframe %>% 
     mutate(ID1 = rep(rows_ID$X1,times= reps)) %>% 
     filter(!(row %in% rows_ID))

#Se definen las columnas del dataframe
df = df %>% 
     separate(X1,into = c("ID_film","Score","Data"), sep = ",") %>%
     separate(Data,into = c("Year","Month","Day"), sep = "-") %>%
     na.omit(df) %>%
     mutate(row=row_number())

#Se eliminan las variables auxiliares
rm(dataframe,rows,rows_ID,IDs,reps)

#Se ordenan las posiciones de las columnas y se indican su nuevo nombre
df = df[, c(6, 7, 1, 2, 3,4,5)]
df = df %>% 
     rename(
      MovieID = ID1,
      CustomerID = ID_film,
      Rating = Score,
      Idx = row
     )

#Se elimina el caracter ':' de la columna del MovieID
df$MovieID = unlist(strsplit(df$MovieID , split = ':', fixed=FALSE))


#Se importa el dataframe de los datos de las películas
n_mov = 10
df_movies = read_csv("data/movie_titles.csv", col_names = FALSE, n_max = n_mov)
```



Visualizo la tabla

```{r}
knitr::kable(df)
```

